@startuml
'skinparam monochrome true
skinparam fontClassColor white
skinparam component {
  FontColor white
}

actor Аналитик as analyst
database "Репозиторий с API" as repo
actor Разработчик as dev
participant Nexus as nexus

analyst -> repo: Pull Request
dev --> analyst: Code Review
alt Ревью пройдено
analyst -> repo: Merge Pull Request
repo -> nexus: Jar с контрактами
nexus -> dev: Jar с контрактами
end
@enduml