@startuml
skinparam monochrome reverse
actor Аналитик as analyst
database "Репозиторий с API" as repo
actor Разработчик as dev
participant Registry as nexus

analyst -> repo: Pull Request
dev --> analyst: Code Review
alt Ревью пройдено
analyst -> repo: Merge Pull Request
repo -> nexus: Артефакт
nexus -> dev: Артефакт
end
@enduml