@startuml create_ticket

skinparam monochrome reverse
title "Create Ticket"

box Frontend $frontendColor
    actor "Оператор" as user order 10
    participant "Web-Client" as client order 20
end box

box Backend $backendColor
    participant "Service" as service order 30
    database "Database" as db order 40
end box

group Создание обращения
    activate client
        user -> client: Вызов принят
        user -> client: Нажата кнопка "Создать обращение"

        client -> client: Проверка наличия активного звонка

        alt $failureBackgroundColor Failure: Нет активного звонка
            client --> user: Вернуть ошибку отсутствия звонка
        else $successBackgroundColor Success: Активный звонок есть
            client -> service: Вызвать метод [[$mutationCssdTicketsCreate Создать обращение]]
            activate service
                service -> db: Создать обращение в таблице [[$ticketsTable tickets]]
                service -> db: Создать запись в таблице [[$eventsOutbox events_outbox]]
                service --> client: Вернуть ответ с атрибутами созданного обращения
            deactivate service
            client --> user: Открыть карточку обращения для заполнения
        end
    deactivate client
end
@enduml